name: backend
language: python
variables:
  - name: MONGO_USER
    inputType: Secret
    multiline: false
    defaultValue: MONGO_USER
    required: true
  - name: MONGO_PASSWORD
    inputType: Secret
    multiline: false
    defaultValue: MONGO_PASSWORD
    required: true
  - name: MONGO_HOST
    inputType: FreeText
    multiline: false
    defaultValue: mongodb
    required: true
  - name: Quix__BlobStorage__Connection__Json
    inputType: Secret
    multiline: false
    defaultValue: Quix__BlobStorage__Connection__Json
    required: true
  - name: INFLUXDB_USER
    inputType: Secret
    multiline: false
    defaultValue: INFLUXDB_USER
    required: true
  - name: INFLUXDB_PASSWORD
    inputType: Secret
    multiline: false
    defaultValue: INFLUXDB_PASSWORD
    required: true
  - name: INFLUXDB_HOST
    inputType: FreeText
    multiline: false
    defaultValue: influxdb
    required: true
  - name: INFLUXDB_PORT
    inputType: FreeText
    multiline: false
    defaultValue: 8086
    required: true
  - name: CONFIG_API_URL
    inputType: FreeText
    multiline: false
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
