name: labview-sim
language: python
variables:
  - name: TEST_API_URL
    inputType: FreeText
    multiline: false
  - name: ECU_API_URL
    inputType: FreeText
    multiline: false
    defaultValue: https://ecu-quixers-testrigdemotestrigsimulator-prod.az-france-0.app.quix.io/ecu/start
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: web-api-gateway
